parameters:
    database_driver: pdo_mysql
    database_host: localhost
    database_port: null
    database_name: jcsgykadmin
    database_user: root
    database_password: null
    mailer_transport: smtp
    mailer_host: localhost
    mailer_user: null
    mailer_password: null
    locale: en
    secret: 109cd42bcd931f86fcb97cad1c2664167
    database_path: null
