parameters:
    param_groups:
        1: "Érdeklődés típusok"
        2: "Szolgáltatók"
        3: "Végzettség"
        4: "Gazdasági aktivitás"
        5: "Családi összetétel"
        6: "Problémák"
        7: "Esemény megnevezés"
        8: "Esetkezelés jellege"
        9: "Továbbirányítások"
        10: "Esemény, Egyéb tevékenység"
        11: "Lezárások"
        12: "Újranyitás"

