parameters:
    system_parameter_groups:
        # key: ["name", required, type (normal, multiple, table)]
        inquiry: ["Érdeklődés típusok", 0, 0]
        citizenship: ["Állampolgárság", 0, 0]
        citizenship_status: ["Állampolgársági jogállás", 0, 0]
        client_archives: ["Ügyfél archiválások", 0, 0]
        client_reopens: ["Ügyfél újranyitás", 0, 0]
        problem_closings: ["Probléma lezárások", 0, 0]
        events: ["Esemény", 0, 0]
        signals: ["Jelzések", 0, 0]
        lunch_types: ["Ebéd Típusok", 0, 0]
        social_workers: ["Gondozók", 0, 0]
        homehelp_services: ["Gondozás szolgáltatások", 0, 0]
        handicaps: ["Fogyatékosságok", 0, 0]
        club_events: ["Klub események", 0, 0]

    task_status:
        1: "új"
        2: "folyamatban"
        3: "kész"

    stat_events:
        # Stat::TYPE_FAMILY_HELP
        2:
            1: "Új megkeresés"
            2: "Feldolgozott esemény"

    kenyszi_url: 'http://localhost/kenyszi-szerver/'