parameters:
#    param_groups:
#        1:  "Érdeklődés típusok"
#        2:  "Szolgáltatók"
#        3:  "Végzettség"
#        4:  "Gazdasági aktivitás"
#        5:  "Családi összetétel"
#        6:  "Problémák"
#        7:  "Esemény megnevezés"
#        8:  "Esetkezelés jellege"
#        9:  "Továbbirányítások"
#        10: "Esemény, Egyéb tevékenység"
#        11: "Ügyfél archiválások"
#        12: "Ügyfél újranyitás"
#        13: "Probléma lezárások"
#        14: "Állampolgárság"
#        15: "Állampolgársági jogállás"

    task_status:
        1: "új"
        2: "folyamatban"
        3: "kész"

    stat_events:
        # Stat::TYPE_FAMILY_HELP
        2:
            1: "Új megkeresés"
            2: "Feldolgozott esemény"
            
    kenyszi_url: 'http://localhost/kenyszi-szerver/'